### ISSUE TITLE
DataUriVisitor doesn't use relative paths

### ISSUE THREAD

**Issue by AWallace327** [bingnz/gulp-less-changed#27]
Using the plugin currently causes an error for me. My file structure is generalised as follows:
Content/Product/main.less (Entry Point):
`@import "../Thirdparty/other.less"`

Content/Thirdparty/other.less:
`background-image: data-uri(other.svg)`

where other.svg is a file in Content/ThirdParty/

During processing it adds the import as 
`{ directoryName: "Content/Product", relativePath: "other.svg"}`
and as a result it causes an error because the file can't be found.
It should be
`{ directoryName: "Content/ThirdParty", relativePath: "other.svg"}`

Changing `var entryPath = fileInfo.entryPath;` to `var entryPath = fileInfo.currentDirectory;` (Line 43, data-uri-visitor.js) fixes the issue.

Is this by design or can this fix be implemented?

**Comment by bingnz** [comment]
Thanks @AWallace327; if the less compiler itself copes with that location and produces the desired .css then the plugin should cope with it as well. I'll take a look and see if I can reproduce it.

**Comment by AWallace327** [comment]
Great! Thank you. 

Awesome plugin, btw. Made my builds noticeably faster.

**Comment by bingnz** [comment]
Thanks! Great to hear it's sped things up for you :)
