### ISSUE TITLE
The ability to use the gulp-less-changed without  data-uri

### ISSUE THREAD

**Issue by MargoNikk** [bingnz/gulp-less-changed#43]
hi there

I have a different level of nesting of less files and imports in my project. And when the plugin checks the data-uri, it checks the validity of the URL. But (because of the different level of nesting of files) this may be an invalid URL and then the plugin will return an error. If you put the correct URL - less will not compile base64 from this URL

_An simple example:_
file _variables.less ( ./styles/base/_variables.less) 
`@icon: data-uri(../../img/icon.svg);`

file styles.less (./styles/styles.less)
`@import 'base/_variables'`

and icon.svg (./img/icon.svg)

In this case plugin will ok, but in the sourse file data-uri dont compile becouse its invalid url for source file. 
if we put `@icon: data-uri(../img/icon.svg);` Plugin will return an error

Maybe you have an idea how to fix this? Or you can add to the plugin the ability to disable the data-uri. it would be great!
thank

**Comment by bingnz** [comment]
Hi @MargoNikk,

I can't really tell from your description what's going on here.
As you can see in [this test](https://github.com/bingnz/gulp-less-changed/blob/master/test/list-imports-cases/file-with-data-uri/file.less), the plugin does support `data-uri`.

To help troubleshoot this:
- Does it work as you expect if you don't use the `gulp-less-changed` plugin at all? In other words, does the less plugin support what you're trying to do?
- All the examples I've seen for using `data-uri` have the path in [quotes](http://lesscss.org/functions/#misc-functions-data-uri). Have you tried using quotes?

If you try the above and it does work with less itself but not with the plugin, then please attach a .zip file and I can take a look.

Thanks,
David

**Comment by MargoNikk** [comment]
Hello, @bingnz ,

Sorry, I will try to explain in more detail.
In the example above, I really forgot the quotes. But it does not matter. because in the real example there are quotes. and plugin I use as it should
The plugin works as expected and works well! Thank you for it.

But I have issue with data-uri. I attach an example file with code comments.
[v_example.zip](https://github.com/bingnz/gulp-less-changed/files/3390117/v_example.zip)

Now there is a code that I need. Compilation result: http://joxi.ru/Q2K4X37CLaaLNA
if we fix it we will follow this:
1)http://joxi.ru/82QM815TwbbyO2
2) Result: http://joxi.ru/EA41wGvToqqo1r

It would be great to be able to turn off the compilation of datа-uri if desired.

Thanks,
Margo

**Comment by bingnz** [comment]
Hi @MargoNikk,

Thanks for the detailed information!
I can prepare a fix for this. In the meantime there are a couple of workarounds.
1. You can use the less [rewriteUrls](http://lesscss.org/usage/#less-options-rewrite-urls) option, like this: 
[rewrite-urls-option.zip](https://github.com/bingnz/gulp-less-changed/files/3390337/rewrite-urls-option.zip).
2. You can make the URLs relative to the root, like this: 
[urls-made-relative-to-root.zip](https://github.com/bingnz/gulp-less-changed/files/3390338/urls-made-relative-to-root.zip).

Thanks,
David

**Comment by bingnz** [comment]
@MargoNikk please feel free to reopen this or create another issue if it doesn't solve your problem.

**Comment by MargoNikk** [comment]
Hello, @bingnz ! 

Thank you so much for the advices and for the fix! Evrything is work and good:)

Best Regards,
Margo
